"use client";

import { useState } from 'react';
import { useForm, type SubmitHandler } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from "@/hooks/use-toast";
import { aiDietPlan, type AIDietPlanInput, type AIDietPlanOutput } from '@/ai/flows/ai-diet-plan';
import { Loader2, UtensilsCrossed } from 'lucide-react';

const dietPlanSchema = z.object({
  dietaryRestrictions: z.string().min(3, "Please describe any dietary restrictions."),
  preferences: z.string().min(3, "Please list your food preferences."),
  healthGoals: z.string().min(3, "What are your health goals?"),
});

export default function AIDietPlanForm() {
  const [isLoading, setIsLoading] = useState(false);
  const [dietPlanResult, setDietPlanResult] = useState<AIDietPlanOutput | null>(null);
  const { toast } = useToast();

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<AIDietPlanInput>({
    resolver: zodResolver(dietPlanSchema),
  });

  const onSubmit: SubmitHandler<AIDietPlanInput> = async (data) => {
    setIsLoading(true);
    setDietPlanResult(null);
    try {
      const result = await aiDietPlan(data);
      setDietPlanResult(result);
      toast({
        title: "Diet Plan Generated!",
        description: "Your personalized diet plan is ready.",
      });
      reset(); 
    } catch (error) {
      console.error("Error generating diet plan:", error);
      toast({
        title: "Error",
        description: "Failed to generate diet plan. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="w-full max-w-lg mx-auto shadow-lg">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 font-headline text-2xl">
          <UtensilsCrossed className="h-6 w-6 text-primary" />
          Create Your AI Diet Plan
        </CardTitle>
        <CardDescription>
          Fill in your details to get a personalized diet plan generated by our AI.
        </CardDescription>
      </CardHeader>
      <form onSubmit={handleSubmit(onSubmit)}>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="dietaryRestrictions">Dietary Restrictions</Label>
            <Textarea
              id="dietaryRestrictions"
              placeholder="e.g., vegan, gluten-free, allergies to nuts"
              {...register('dietaryRestrictions')}
              className={errors.dietaryRestrictions ? 'border-destructive' : ''}
            />
            {errors.dietaryRestrictions && (
              <p className="text-sm text-destructive">{errors.dietaryRestrictions.message}</p>
            )}
          </div>
          <div className="space-y-2">
            <Label htmlFor="preferences">Food Preferences</Label>
            <Textarea
              id="preferences"
              placeholder="e.g., love fruits, prefer chicken over fish, dislike spicy food"
              {...register('preferences')}
              className={errors.preferences ? 'border-destructive' : ''}
            />
            {errors.preferences && (
              <p className="text-sm text-destructive">{errors.preferences.message}</p>
            )}
          </div>
          <div className="space-y-2">
            <Label htmlFor="healthGoals">Health Goals</Label>
            <Textarea
              id="healthGoals"
              placeholder="e.g., weight loss, muscle gain, maintain current weight"
              {...register('healthGoals')}
              className={errors.healthGoals ? 'border-destructive' : ''}
            />
            {errors.healthGoals && (
              <p className="text-sm text-destructive">{errors.healthGoals.message}</p>
            )}
          </div>
        </CardContent>
        <CardFooter>
          <Button type="submit" className="w-full bg-primary hover:bg-primary/90 text-primary-foreground" disabled={isLoading}>
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating Plan...
              </>
            ) : (
              'Get Diet Plan'
            )}
          </Button>
        </CardFooter>
      </form>
      {dietPlanResult && (
        <CardContent className="mt-6 border-t pt-6">
          <h3 className="font-headline text-xl font-semibold mb-2">Your Personalized Diet Plan:</h3>
          <pre className="whitespace-pre-wrap bg-muted p-4 rounded-md text-sm text-muted-foreground font-body">
            {dietPlanResult.dietPlan}
          </pre>
        </CardContent>
      )}
    </Card>
  );
}
